//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pipeliner.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pipeliner.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify pipeline in configuration: it cannot be null.
        /// </summary>
        internal static string PipelineDescriptionValidation_IsNull {
            get {
                return ResourceManager.GetString("PipelineDescriptionValidation_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify names for all pipelines.
        /// </summary>
        internal static string PipelineDescriptionValidation_NameShouldBeNotEmpty {
            get {
                return ResourceManager.GetString("PipelineDescriptionValidation_NameShouldBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify starter for pipeline &apos;{0}&apos;. Starter is a mandatory field and cannot be skipped.
        /// </summary>
        internal static string PipelineDescriptionValidation_StarterIsRequired {
            get {
                return ResourceManager.GetString("PipelineDescriptionValidation_StarterIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline &apos;{0}&apos;: first step should have no trigger defined.
        /// </summary>
        internal static string PipelineDescriptionValidator_PipelineFirstStepShouldHaveNoTriggerDefined {
            get {
                return ResourceManager.GetString("PipelineDescriptionValidator_PipelineFirstStepShouldHaveNoTriggerDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline &apos;{0}&apos; should have at least one step.
        /// </summary>
        internal static string PipelineDescriptionValidator_PipelineShouldHaveAtLeastOneStep {
            get {
                return ResourceManager.GetString("PipelineDescriptionValidator_PipelineShouldHaveAtLeastOneStep", resourceCulture);
            }
        }
    }
}
